In [1]:
!nvidia-smi

Tue Apr 21 16:49:04 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.95                 Driver Version: 581.95         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   54C    P8             17W /   45W |     823MiB /   8192MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1132    C+G   ..._pzs8sxrjxfjjc\app\claude.exe      N/A      |
|    0   N/A  N/A            1620    C+G   ...yb3d8bbwe\Notepad\Notepad.exe      N/A      |
|    0   N/A  N/A            3908    C+G   ...e Experience\NVIDIA Share.exe      N/A      |
|    0   N/A  N/A            5852    C+G   ...indows\System32\ShellHost.exe      N/A      |
|    0   N/A  N/A            6176    C+G   ....0.3912.60\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           11624    C+G   ...8bbwe\WsaClient\WsaClient.exe      N/A      |
|    0   N/A  N/A           12500    C+G   ...xyewy\ShellExperienceHost.exe      N/A      |
|    0   N/A  N/A           12652    C+G   C:\Windows\explorer.exe               N/A      |
|    0   N/A  N/A           13056    C+G   ...2txyewy\CrossDeviceResume.exe      N/A      |
|    0   N/A  N/A           13852    C+G   ...5n1h2txyewy\TextInputHost.exe      N/A      |
|    0   N/A  N/A           15976    C+G   ...0_x64__htrsf667h5kn2\AWCC.exe      N/A      |
|    0   N/A  N/A           16880    C+G   ..._cw5n1h2txyewy\SearchHost.exe      N/A      |
|    0   N/A  N/A           16888    C+G   ...y\StartMenuExperienceHost.exe      N/A      |
|    0   N/A  N/A           18552    C+G   ....0.3912.60\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           20812    C+G   ...Chrome\Application\chrome.exe      N/A      |
|    0   N/A  N/A           22984    C+G   ..._pzs8sxrjxfjjc\app\claude.exe      N/A      |
|    0   N/A  N/A           25324    C+G   ...l\slack\app-4.44.65\slack.exe      N/A      |
|    0   N/A  N/A           27212    C+G   ...App_cw5n1h2txyewy\LockApp.exe      N/A      |
|    0   N/A  N/A           28908    C+G   ...2p2nqsd0c76g0\app\ChatGPT.exe      N/A      |
|    0   N/A  N/A           29272    C+G   ...1g1gvanyjgm\WhatsApp.Root.exe      N/A      |
|    0   N/A  N/A           36052    C+G   ...ms\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A           36416    C+G   ...cord\app-1.0.9233\Discord.exe      N/A      |
|    0   N/A  N/A           37020    C+G   ...Chrome\Application\chrome.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [2]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting datasets>=2.0.0 (from evaluate)
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (1.23.5)
Requirement already satisfied: dill in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (0.4.0)
Requirement already satisfied: pandas in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (4.67.1)
Collecting xxhash (from evaluate)
  Using cached xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess (from evaluate)
  Using cached multiprocess-0.70.19-py311-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec>=2021.05.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Collecting huggingface-hub>=0.7.0 (from evaluate)
  Downloading huggingface_hub-1.11.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from evaluate) (23.2)
Requirement already satisfied: filelock in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from datasets>=2.0.0->evaluate) (3.20.1)
Collecting pyarrow>=21.0.0 (from datasets>=2.0.0->evaluate)
  Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: httpx<1.0.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: anyio in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.0)
Requirement already satisfied: certifi in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2024.12.14)
Requirement already satisfied: httpcore==1.* in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub>=0.7.0->evaluate)
  Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: typer in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.20.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Collecting dill (from evaluate)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from requests>=2.19.0->evaluate) (2.6.2)
Requirement already satisfied: colorama in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from pandas->evaluate) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 527.0/527.0 kB 16.6 MB/s  0:00:00
Downloading huggingface_hub-1.11.0-py3-none-any.whl (645 kB)
   ---------------------------------------- 0.0/645.5 kB ? eta -:--:--
   ---------------------------------------- 645.5/645.5 kB 25.6 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---------------------------------------- 3.7/3.7 MB 36.3 MB/s  0:00:00
Downloading multiprocess-0.70.19-py311-none-any.whl (144 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------- ----------------------- 11.5/27.3 MB 55.5 MB/s eta 0:00:01
   ------------------------------- -------- 21.2/27.3 MB 51.5 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 46.7 MB/s  0:00:00
Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Installing collected packages: xxhash, pyarrow, hf-xet, dill, multiprocess, huggingface-hub, datasets, evaluate

  Attempting uninstall: pyarrow

    Found existing installation: pyarrow 11.0.0

   ----- ---------------------------------- 1/8 [pyarrow]
    Uninstalling pyarrow-11.0.0:
   ----- ---------------------------------- 1/8 [pyarrow]
      Successfully uninstalled pyarrow-11.0.0
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ----- ---------------------------------- 1/8 [pyarrow]
   ---------- ----------------------------- 2/8 [hf-xet]
  Attempting uninstall: dill
   ---------- ----------------------------- 2/8 [hf-xet]
    Found existing installation: dill 0.4.0
   ---------- ----------------------------- 2/8 [hf-xet]
    Uninstalling dill-0.4.0:
   ---------- ----------------------------- 2/8 [hf-xet]
      Successfully uninstalled dill-0.4.0
   ---------- ----------------------------- 2/8 [hf-xet]
   --------------- ------------------------ 3/8 [dill]
   --------------- ------------------------ 3/8 [dill]
   --------------- ------------------------ 3/8 [dill]
   --------------- ------------------------ 3/8 [dill]
   --------------- ------------------------ 3/8 [dill]
   -------------------- ------------------- 4/8 [multiprocess]
   -------------------- ------------------- 4/8 [multiprocess]
   -------------------- ------------------- 4/8 [multiprocess]
   -------------------- ------------------- 4/8 [multiprocess]
   -------------------- ------------------- 4/8 [multiprocess]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ------------------------------ --------- 6/8 [datasets]
   ----------------------------------- ---- 7/8 [evaluate]
   ----------------------------------- ---- 7/8 [evaluate]
   ----------------------------------- ---- 7/8 [evaluate]
   ---------------------------------------- 8/8 [evaluate]

Successfully installed datasets-4.8.4 dill-0.4.1 evaluate-0.4.6 hf-xet-1.4.3 huggingface-hub-1.11.0 multiprocess-0.70.19 pyarrow-24.0.0 xxhash-3.6.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlflow 2.3.2 requires pyarrow<12,>=4.0.0, but you have pyarrow 24.0.0 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install transformers[sentencepiece] datasets sacrebleu -q

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install --upgrade accelerate
!pip install uninstall -y transformers accelerate

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (1.23.5)
Requirement already satisfied: packaging>=20.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (23.2)
Requirement already satisfied: psutil in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (7.1.3)
Requirement already satisfied: pyyaml in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (6.0.3)
Collecting torch>=2.0.0 (from accelerate)
  Downloading torch-2.11.0-cp311-cp311-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (1.11.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typer in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.20.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.0)
Requirement already satisfied: certifi in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2024.12.14)
Requirement already satisfied: httpcore==1.* in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (65.5.0)
Collecting sympy>=1.13.3 (from torch>=2.0.0->accelerate)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.0.0->accelerate)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.0.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Downloading torch-2.11.0-cp311-cp311-win_amd64.whl (114.5 MB)
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   --- ------------------------------------ 9.7/114.5 MB 50.5 MB/s eta 0:00:03
   ------- -------------------------------- 21.0/114.5 MB 51.0 MB/s eta 0:00:02
   ---------- ----------------------------- 31.2/114.5 MB 52.1 MB/s eta 0:00:02
   ------------- -------------------------- 39.6/114.5 MB 49.3 MB/s eta 0:00:02
   ----------------- ---------------------- 50.3/114.5 MB 49.3 MB/s eta 0:00:02
   -------------------- ------------------- 59.8/114.5 MB 48.2 MB/s eta 0:00:02
   ------------------------ --------------- 69.5/114.5 MB 48.2 MB/s eta 0:00:01
   ---------------------------- ----------- 80.7/114.5 MB 49.1 MB/s eta 0:00:01
   -------------------------------- ------- 92.0/114.5 MB 49.8 MB/s eta 0:00:01
   ----------------------------------- --- 103.0/114.5 MB 49.8 MB/s eta 0:00:01
   --------------------------------------  111.7/114.5 MB 49.2 MB/s eta 0:00:01
   ---------------------------------------- 114.5/114.5 MB 46.0 MB/s  0:00:02
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------- 6.3/6.3 MB 43.1 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 17.1 MB/s  0:00:00
Installing collected packages: mpmath, sympy, torch, accelerate

   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -y

In [ ]:
!pip install transformers accelerate
!pip install nltk

Requirement already satisfied: transformers in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (5.5.4)
Requirement already satisfied: accelerate in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (0.20.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.0)
Requirement already satisfied: certifi in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.12.14)
Requirement already satisfied: httpcore==1.* in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: psutil in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (7.1.3)
Requirement already satisfied: torch>=2.0.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: setuptools<82 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.0.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\theva\documents\github\mlops-course\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

If the block below

In [8]:
from transformers import pipeline,set_seed
from datasets import load_dataset, load_from_disk
from matplotlib.pyplot import plot
import pandas as pd

from transformers import AutoModelForSeq2SeqLM,AutoTokenizer
import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\theVa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [9]:
from transformers import AutoTokenizer, PegasusForConditionalGeneration


model = PegasusForConditionalGeneration.from_pretrained("google/pegasus-xsum")
#converts words to tokens
tokenizer = AutoTokenizer.from_pretrained("google/pegasus-xsum")

ARTICLE_TO_SUMMARIZE = (
    "The recent discovery of a new exoplanet, Kepler-186f, has excited the scientific community. "
    "This Earth-sized planet orbits a red dwarf star in the habitable zone, meaning liquid water could exist on its surface. "
    "While direct observation is currently impossible, researchers are using advanced techniques to infer its characteristics. "
    "This finding marks a significant step in the search for extraterrestrial life and understanding planetary formation."
)

inputs = tokenizer(ARTICLE_TO_SUMMARIZE, max_length=1024, return_tensors="pt")

# Generate Summary with adjusted length parameters
summary_ids = model.generate(inputs["input_ids"], max_length=150, min_length=30, num_beams=5, early_stopping=True)
summary = tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print(summary)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\theVa\Documents\GitHub\mlops-course\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\theVa\.cache\huggingface\hub\models--google--pegasus-xsum. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 680/680 [00:00<00:00, 22245.40it/s]
PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-xsum
Key                                  | Status  |
-------------------------------------+---------+-
model.decoder.embed_positions.weight | MISSING |
model.encoder.embed_positions.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In our series of letters from African journalists, film-maker and columnist Ahmed Rashid looks at the latest discoveries in the search for life beyond Earth.

In [11]:
from transformers import AutoModelForSeq2SeqLM,AutoTokenizer
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [12]:
model = 'google/pegasus-cnn_dailymail'
tokenizer = AutoTokenizer.from_pretrained(model)
#move to gpu for faster processing
model = AutoModelForSeq2SeqLM.from_pretrained(model).to(device)

'[WinError 10054] An existing connection was forcibly closed by the remote host' thrown while requesting HEAD https://huggingface.co/google/pegasus-cnn_dailymail/resolve/main/config.json
Retrying in 1s [Retry 1/5].
c:\Users\theVa\Documents\GitHub\mlops-course\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\theVa\.cache\huggingface\hub\models--google--pegasus-cnn_dailymail. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
You are using a model of type `pegasus` to instantiate a model of type ``. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.

ValueError: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece or tiktoken installed to convert a slow tokenizer to a fast one.

In [21]:
!wget https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip

--2026-04-21 13:45:29--  https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/krishnaik06/datasets/refs/heads/main/summarizer-data.zip [following]
--2026-04-21 13:45:29--  https://raw.githubusercontent.com/krishnaik06/datasets/refs/heads/main/summarizer-data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7903594 (7.5M) [application/zip]
Saving to: ‘summarizer-data.zip.1’

summarizer-data.zip 100%[===================>]   7.54M  1.60MB/s    in 4.7s

2026-04-21 13:45:34 (1.60 MB/s) - ‘summarizer-data.zip.1’ saved [7903594/7903594]

unzip:  cannot find or open summarizer-data.zip.zip, summarizer-data.zip.zip.zip or summarizer-data.zip.zip.ZIP.

In [22]:
!unzip summarizer-data.zip

Archive:  summarizer-data.zip
  inflating: samsum-test.csv
  inflating: samsum-train.csv
  inflating: samsum-validation.csv
   creating: samsum_dataset/
 extracting: samsum_dataset/dataset_dict.json
   creating: samsum_dataset/test/
  inflating: samsum_dataset/test/data-00000-of-00001.arrow
  inflating: samsum_dataset/test/dataset_info.json
  inflating: samsum_dataset/test/state.json
   creating: samsum_dataset/train/
  inflating: samsum_dataset/train/data-00000-of-00001.arrow
  inflating: samsum_dataset/train/dataset_info.json
  inflating: samsum_dataset/train/state.json
   creating: samsum_dataset/validation/
  inflating: samsum_dataset/validation/data-00000-of-00001.arrow
  inflating: samsum_dataset/validation/dataset_info.json
  inflating: samsum_dataset/validation/state.json

In [23]:
dataset_samsum = load_from_disk('samsum_dataset')
dataset_samsum

DatasetDict({
    train: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 14732
    })
    test: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 819
    })
    validation: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 818
    })
})

In [24]:
split_lengths = [len(dataset_samsum[split]) for split in dataset_samsum]

print(f'Split lengths: {split_lengths}')
print(f'Features: {dataset_samsum["train"].column_names}')
print('\nDialogue')
print(dataset_samsum['test'][1]['dialogue'])
print('\nSummary')
print(dataset_samsum['test'][1]['summary'])

Split lengths: [14732, 819, 818]
Features: ['id', 'dialogue', 'summary']

Dialogue
Eric: MACHINE!
Rob: That's so gr8!
Eric: I know! And shows how Americans see Russian ;)
Rob: And it's really funny!
Eric: I know! I especially like the train part!
Rob: Hahaha! No one talks to the machine like that!
Eric: Is this his only stand-up?
Rob: Idk. I'll check.
Eric: Sure.
Rob: Turns out no! There are some of his stand-ups on youtube.
Eric: Gr8! I'll watch them now!
Rob: Me too!
Eric: MACHINE!
Rob: MACHINE!
Eric: TTYL?
Rob: Sure :)

Summary
Eric and Rob are going to watch a stand-up on youtube.

In [28]:
def convert_examples_to_features(examples_batch):
  input_encodings = tokenizer(examples_batch['dialogue'],max_length=1024,truncation=True)

  # Removed 'with tokenizer.as_target_tokenizer():' as PegasusTokenizer does not have this attribute
  target_encodings = tokenizer(examples_batch['summary'],max_length=128,truncation=True)

  return {'input_ids': input_encodings['input_ids'],
          'attention_mask': input_encodings['attention_mask'],
          'labels': target_encodings['input_ids']}

In [29]:
dataset_samsum_pt = dataset_samsum.map(convert_examples_to_features,batched=True)

Map:   0%|          | 0/14732 [00:00<?, ? examples/s]

Map:   0%|          | 0/819 [00:00<?, ? examples/s]

Map:   0%|          | 0/818 [00:00<?, ? examples/s]

In [30]:
dataset_samsum_pt['train']

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 14732
})

In [32]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer,model=model)

In [36]:
from transformers import TrainingArguments, Trainer

trainer_args = TrainingArguments(
    output_dir = 'pegasus-samsum',num_train_epochs=1, warmup_steps=500,
    per_device_train_batch_size=1, per_device_eval_batch_size=1,
    weight_decay=0.01, logging_steps=10,
    eval_strategy='steps', eval_steps=500, save_steps=1e6,
    gradient_accumulation_steps=16
)

trainer = Trainer(model=model,args=trainer_args,data_collator=data_collator,
                  train_dataset=dataset_samsum_pt['test'],
                  eval_dataset=dataset_samsum_pt['validation'])

In [37]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=52, training_loss=183.6049678509052, metrics={'train_runtime': 713.5084, 'train_samples_per_second': 1.148, 'train_steps_per_second': 0.073, 'total_flos': 336188055896064.0, 'train_loss': 183.6049678509052, 'epoch': 1.0})

In [39]:


def generate_batch_sized_chunks(elements, batch_size):
  for i in range(0,len(elements),batch_size):
    yield elements[i:i+batch_size]


def calculate_metric_on_test_ds(dataset,metric,model,tokenizer,batch_size=16,device=device,
                                column_text='article',column_summary='highlights'):
  article_batches = list(generate_batch_sized_chunks(dataset[column_text],batch_size))
  target_batches = list(generate_batch_sized_chunks(dataset[column_summary],batch_size))

  for article_batch, target_batch in tqdm(zip(article_batches,target_batches),total=len(article_batches)):
    inputs = tokenizer(
                        article_batch,
                        max_length=1024,
                        truncation=True,
                        padding='max_length',
                        return_tensors='pt'
                      )
    summaries = model.generate(input_ids=inputs['input_ids'].to(device),
    attention_mask = inputs['attention_mask'].to(device),
    length_penalty=0.8, num_beans = 8, max_length = 128)

  decoded_summaries = [tokenizer.decode(s,skip_special_tokens=True,clean_up_tokenization_spaces=True) for s in summaries]

  decoded_summaries = [d.replace('',' ') for d in decoded_summaries]
  metric.add_batch(predictions=decoded_summaries,references=target_batch)

  score = metric.compute()
  return score

In [40]:
!pip install evaluate

Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.10.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)

In [46]:
def generate_batch_sized_chunks(elements, batch_size):
  for i in range(0,len(elements),batch_size):
    yield elements[i:i+batch_size]


def calculate_metric_on_test_ds(dataset,metric,model,tokenizer,batch_size=16,device=device,
                                column_text='article',column_summary='highlights'):
  article_batches = list(generate_batch_sized_chunks(dataset[column_text],batch_size))
  target_batches = list(generate_batch_sized_chunks(dataset[column_summary],batch_size))

  for article_batch, target_batch in tqdm(zip(article_batches,target_batches),total=len(article_batches)):
    inputs = tokenizer(
                        article_batch,
                        max_length=1024,
                        truncation=True,
                        padding='max_length',
                        return_tensors='pt'
                      )
    summaries = model.generate(input_ids=inputs['input_ids'].to(device),
    attention_mask = inputs['attention_mask'].to(device),
    length_penalty=0.8, num_beams = 8, max_length = 128)

  decoded_summaries = [tokenizer.decode(s,skip_special_tokens=True,clean_up_tokenization_spaces=True) for s in summaries]

  decoded_summaries = [d.replace('',' ') for d in decoded_summaries]
  metric.add_batch(predictions=decoded_summaries,references=target_batch)

  score = metric.compute()
  return score

!pip install rouge_score
import evaluate
rouge_metric = evaluate.load('rouge')
rouge_names = ['rouge1','rouge2','rougeL','rougeLsum']

score = calculate_metric_on_test_ds(dataset_samsum_pt['test'][0:10],rouge_metric,trainer.model,tokenizer,batch_size=2,column_text='dialogue',column_summary='summary')

rogue_dict = {rn:score[rn] for rn in rouge_names}
import pandas as pd
pd.DataFrame(rogue_dict,index=[f'pegasus'])

Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)

100%|██████████| 5/5 [00:54<00:00, 10.99s/it]

           rouge1  rouge2    rougeL  rougeLsum
pegasus  0.015662     0.0  0.015662   0.015662

In [49]:
saved_model_name = 'custom-pegasus-samsum'

In [48]:
model.save_pretrained(saved_model_name)
tokenizer.save_pretrained('tokenizer')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('tokenizer/tokenizer_config.json', 'tokenizer/tokenizer.json')

In [56]:
from transformers import pipeline

In [62]:
gen_kwargs = {'length_penalty':0.8,'num_beams':8,'max_length':128}

sample_text = dataset_samsum['test'][0]['dialogue']
reference = dataset_samsum['test'][0]['summary']

# Removed pipeline due to 'Unknown task summarization' error and used direct model generation.
inputs = tokenizer(sample_text, max_length=1024, return_tensors="pt", truncation=True)
summary_ids = model.generate(inputs["input_ids"].to(device), **gen_kwargs)
summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)


print('Dialogue')
print(sample_text)

print('\nReference Summary')
print(reference)

print('\nModel Summary')
print(summary_text)

Dialogue
Hannah: Hey, do you have Betty's number?
Amanda: Lemme check
Hannah: <file_gif>
Amanda: Sorry, can't find it.
Amanda: Ask Larry
Amanda: He called her last time we were at the park together
Hannah: I don't know him well
Hannah: <file_gif>
Amanda: Don't be shy, he's very nice
Hannah: If you say so..
Hannah: I'd rather you texted him
Amanda: Just text him 🙂
Hannah: Urgh.. Alright
Hannah: Bye
Amanda: Bye bye

Reference Summary
Hannah needs Betty's number but Amanda doesn't have it. She needs to contact Larry.

Model Summary
space easyre experience functions her – sector may she best frames first – uniqueren programs law aspect – financial designs even me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well only me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me well me